### ISSUE TITLE
We need chinese!!!

### ISSUE THREAD

**Issue by EinsamPickle** [Pickupppp/DataStructureHomework#1]
没有中文怎么造福后来的同学

**Comment by Pickupppp** [comment]
They are simple




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pickupppp/DataStructureHomework"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 晚上6:01
收件人:&nbsp;"Pickupppp/DataStructureHomework"<DataStructureHomework@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Pickupppp/DataStructureHomework] We need chinese!!! (#1)





 
没有中文怎么造福后来的同学
